# Generated by Django 3.0.7 on 2020-06-13 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre',
            new_name='FileSystem',
        ),
    ]
